# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 25488eeed35081bbf9b89cd92dfdc8fc9476e6ae4ca205c5502da91f932f63ca462f35c59533a649e2d9d3ec15a565683de52ca1aa0f8f31fd39f9d059a71f92

test:
  secret_key_base: 6adfab9eabf84057e0bda843dda3bedb4c843e05cbd7d1f23c1d4fbf67361cc21d8b38a9f2ae9766a01e42bf0db8f62088b240b44ce2b63b526b04f82da833c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
